# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production

on:
  release:
    types: [released, prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      with:
        token:  ${{secrets.PERSONAL_ACCESS_TOKEN}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Version Bumping
      run:  |
         git config --global user.email "version.bumping@email.com"
         git config --global user.name "Version Bumping"
         git remote update
         git fetch
         git checkout --progress --force -B master refs/remotes/origin/master
         npm version minor
         git push
      if: github.event.action=='released'
      
